baseURL = "https://tofu.buzz/"
languageCode = "en-us"
title = "Tofu: The Varieties"

[permalinks]
  type = "/:filename/"

[menu]
  [[menu.main]]
    name = "home/"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "type/"
    pre = "edit"
    url = "/type/"
    weight = 2

[params]
  homeText = ""