baseURL = "https://tofu.buzz/"
languageCode = "en-us"
title = "tofu: the varieties"

[permalinks]
  type = "/:filename/"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "type"
    pre = "edit"
    url = "/type/"
    weight = 2

[params]
  homeText = "quick guide to the types of tofu!"